# Generated by Django 6.0.2 on 2026-04-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Apps', 'Apps'), ('Games', 'Games'), ('Social Media', 'Social Media'), ('Websites', 'Websites')], max_length=50)),
                ('age_group', models.CharField(choices=[('Toddlers', 'Toddlers'), ('Elementary', 'Elementary'), ('Middle School', 'Middle School'), ('Teens', 'Teens')], max_length=50)),
                ('risk_level', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('short_description', models.TextField()),
                ('flagged_reasons', models.JSONField(default=list, help_text='List of reasons why this item is flagged')),
                ('parent_tips', models.JSONField(default=list, help_text='List of tips for parents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-risk_level', 'name'],
            },
        ),
    ]
