# Generated by Django 6.0.3 on 2026-05-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_comment_edited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
