# Generated by Django 6.0.3 on 2026-05-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_forumpost_edited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='category',
            field=models.CharField(choices=[('Games', 'Games'), ('Apps', 'Apps'), ('Trends', 'Trends'), ('Movies', 'Movies'), ('Advice', 'Advice')], default='Advice', max_length=20),
            preserve_default=False,
        ),
    ]
